media:
  input: public/cms/media
  output: public/media
content:
  - name: posts
    label: Posts
    path: public/cms/content/posts
    type: collection
    fields:
      - name: title
        label: Title
        type: string
        required: true
        
      - name: date
        label: Publication Date
        type: date
        time: true
        required: true

      - name: body
        label: Body
        type: rich-text
        required: true

      - name: tags
        label: Tags
        type: string
        list: true
        required: false